language: node_js
node_js:
  - "8"

branches:
  only:
    - src

before_install:
  - npm rebuild node-sass
  - npm install -g gulp-cli

script:
  - npm run build

cache:
  directories:
    - node_modules

notifications:
  email:
    - teemu.vikoren@gmail.com