language: node_js
node_js:
  - "8"

branches:
  only:
    - src

before_install:
  - npm install -g gulp-cli

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

cache:
  directories:
    - node_modules

notifications:
  email:
    - teemu.vikoren@gmail.com